# Disable all warnings that suggest pinning packages, we'll default to updates
# and pin if/when there are errors
ignored:
  - DL3007 # Using latest is prone to errors if the image will ever update.
  - DL3008 # Pin versions in apt get install.
  - DL3013 # Pin versions in pip.
  - DL3016 # Pin versions in npm.
