steps:
- id: 'circleci-base'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - './src/circleci-base'
    - '--tag=${_NAMESPACE}/${_GOOGLE_PROJECT_ID}/circleci-base:${_BRANCH_TAG}'
    - '--tag=${_NAMESPACE}/${_GOOGLE_PROJECT_ID}/circleci-base:${_REVISION_TAG}'
    - '--tag=${_NAMESPACE}/${_GOOGLE_PROJECT_ID}/circleci-base:build-${_BUILD_NUMBER}'
images:
  - '${_NAMESPACE}/${_GOOGLE_PROJECT_ID}/circleci-base:${_BRANCH_TAG}'
  - '${_NAMESPACE}/${_GOOGLE_PROJECT_ID}/circleci-base:${_REVISION_TAG}'
  - '${_NAMESPACE}/${_GOOGLE_PROJECT_ID}/circleci-base:build-${_BUILD_NUMBER}'
