FROM gcr.io/planet-4-151612/circleci-base:${BASE_IMAGE_VERSION}

LABEL authors="Raymond Walker <raymond.walker@greenpeace.org>"

RUN helm init --client-only && \
    helm repo add p4 https://planet4-helm-charts.storage.googleapis.com

COPY --chown=circleci:circleci . /home/circleci/
