FROM gcr.io/planet-4-151612/openresty:${PARENT_VERSION}

LABEL authors="Raymond Walker <raymond.walker@greenpeace.org>"

ENV APP_ENV="${APP_ENVIRONMENT}" \
    APP_HOSTNAME="${APP_HOSTNAME}" \
    PHP_ENABLED="true"

RUN rm -fr /app/source/public && \
    rm -f /app/bin/add_user.sh

COPY --chown=nginx:nginx . /app/
