FROM ${IMAGE_FROM}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

LABEL maintainer=${MAINTAINER} \
      description=${APPLICATION_DESCRIPTION}

ENV CIRCLECI_USER=${CIRCLECI_USER} \
    PATH=/home/${CIRCLECI_USER}/scripts:/home/${CIRCLECI_USER}/google-cloud-sdk/bin:${PATH}

USER root

# hadolint ignore=DL3008
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      gawk \
      gettext \
      default-mysql-client \
      python-pip \
      python-pkg-resources \
      python-setuptools \
      rsync \
      silversearcher-ag \
      vim \
      wget \
      && \
    rm -rf /tmp/* && \
    rm -rf /var/lib/apt/lists/*

RUN pip install \
      yamllint==${YAMLLINT_VERSION} \
      yq==${YQ_VERSION}

RUN git config --global alias.unstaged 'diff --name-only' && \
    git config --global alias.staged 'diff --name-only --cached'

RUN npm install -g \
      bats@${BATS_VERSION} \
      junit-merge@${JUNIT_MERGE_VERSION} \
      tap-xunit@${TAP_XUNIT_VERSION}

WORKDIR /home/${CIRCLECI_USER}

COPY --chown=${CIRCLECI_USER}:${CIRCLECI_USER} .curlrc /home/${CIRCLECI_USER}

RUN mkdir -p scripts && \
    echo "Git Flow v${GIT_FLOW_VERSION} ..." && \
    curl https://raw.githubusercontent.com/petervanderdoes/gitflow-avh/develop/contrib/gitflow-installer.sh | bash -s install version ${GIT_FLOW_VERSION} && \
    rm -fr git-flow && \
    chown -R ${CIRCLECI_USER}:${CIRCLECI_USER} /usr/local/bin

USER ${CIRCLECI_USER}

RUN echo "Hadolint v${HADOLINT_VERSION} ..." && \
    curl -sS "https://github.com/hadolint/hadolint/releases/download/v${HADOLINT_VERSION}/hadolint-Linux-x86_64" -o /usr/local/bin/hadolint && \
    chmod 755 /usr/local/bin/hadolint && \
    echo "Shellcheck v${SHELLCHECK_VERSION} ..." && \
    curl -sS "https://shellcheck.storage.googleapis.com/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" -o /tmp/shellcheck.tar.xz && \
    tar xf /tmp/shellcheck.tar.xz -C /tmp/ && \
    mv /tmp/shellcheck-v${SHELLCHECK_VERSION}/shellcheck /usr/local/bin && \
    echo "Helm v${HELM_VERSION} ..." && \
    curl -sS "https://storage.googleapis.com/kubernetes-helm/helm-v${HELM_VERSION}-linux-amd64.tar.gz" -o /tmp/helm.tar.gz && \
    tar zxf /tmp/helm.tar.gz -C /tmp/ && \
    mv /tmp/linux-amd64/helm /usr/local/bin/helm && \
    echo "Trivy v${TRIVY_VERSION} ..." && \
    curl -sSL https://github.com/knqyf263/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz -o /tmp/trivy.tar.gz && \
    tar zxvf /tmp/trivy.tar.gz -C /tmp/ && \
    mv /tmp/trivy /usr/local/bin && \
    rm -rf /tmp/*

RUN curl -sS "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${GOOGLE_SDK_VERSION}-linux-x86_64.tar.gz" | tar xz && \
    CLOUDSDK_CORE_DISABLE_PROMPTS=1 ./google-cloud-sdk/install.sh \
        --usage-reporting false \
        --bash-completion false \
        --path-update false && \
    gcloud --quiet components update kubectl cloud_sql_proxy && \
    rm -fr /tmp/*

COPY --chown=${CIRCLECI_USER}:${CIRCLECI_USER} ./bin /home/${CIRCLECI_USER}/bin

COPY --chown=${CIRCLECI_USER}:${CIRCLECI_USER} ./scripts /home/${CIRCLECI_USER}/scripts
